Spring security web update
eclipse-tractusx/daps-registration-service pull request #36
Opened 2023-04-24 13:21 UTC by adkumar1

2023-04-24 13:24 UTC, Wulghash commented
Just a simple library update

2023-04-25 11:58 UTC, Siegfriedk commented
> Just a simple library update

Make sure to still review PRs properly. See the wrong version number @Wulghash

2023-04-25 11:58 UTC, Siegfriedk requested changes

2023-04-25 11:58 UTC, Siegfriedk commented on CHANGELOG.md
> +## [2.0.3] - 2023-04-24
version is wrong

2023-04-25 12:12 UTC, adkumar1 commented on CHANGELOG.md
> +## [2.0.3] - 2023-04-24
corrected the version

2023-04-26 08:07 UTC, merged